apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-application.internal.fullname" . }}
  labels: {{- include "web-application.internal.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "web-application.internal.selectorLabels" . | nindent 4 }}
