global:
  domain: c-44453a1.kyma.ondemand.com
  imagePullSecret:
     name: dockerconfigjson-github-com
srv:
  bindings:
    {}
  image:
    registry: ghcr.io
    repository: maxi1555/test3
    tag: '20'
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 100m
      memory: 200M
  health:
    liveness:
      path: /
    readiness:
      path: /
